//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace VDDVendor.ABAServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ABAServiceSoap", Namespace="http://www.lyonsreg.com/WebService/ABAService")]
    public partial class ABAService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateABAOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyABAOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyWireOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBanksForEWOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBanksXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBanksPrimarySortXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBanksXML_W3COperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBanksWithWireXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBanksWithWireXML_W3COperationCompleted;
        
        private System.Threading.SendOrPostCallback FindASCompanyIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindCompanyIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompanyIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogoffOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogonOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequiredLogonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ABAService() {
            this.Url = global::VDDVendor.Properties.Settings.Default.WebMaterialPOC_ABAServices_ABAService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateABACompletedEventHandler ValidateABACompleted;
        
        /// <remarks/>
        public event VerifyABACompletedEventHandler VerifyABACompleted;
        
        /// <remarks/>
        public event VerifyWireCompletedEventHandler VerifyWireCompleted;
        
        /// <remarks/>
        public event GetBanksForEWCompletedEventHandler GetBanksForEWCompleted;
        
        /// <remarks/>
        public event GetBanksXMLCompletedEventHandler GetBanksXMLCompleted;
        
        /// <remarks/>
        public event GetBanksPrimarySortXMLCompletedEventHandler GetBanksPrimarySortXMLCompleted;
        
        /// <remarks/>
        public event GetBanksXML_W3CCompletedEventHandler GetBanksXML_W3CCompleted;
        
        /// <remarks/>
        public event GetBanksWithWireXMLCompletedEventHandler GetBanksWithWireXMLCompleted;
        
        /// <remarks/>
        public event GetBanksWithWireXML_W3CCompletedEventHandler GetBanksWithWireXML_W3CCompleted;
        
        /// <remarks/>
        public event FindASCompanyIDCompletedEventHandler FindASCompanyIDCompleted;
        
        /// <remarks/>
        public event FindCompanyIDCompletedEventHandler FindCompanyIDCompleted;
        
        /// <remarks/>
        public event GetCompanyIDCompletedEventHandler GetCompanyIDCompleted;
        
        /// <remarks/>
        public event LogoffCompletedEventHandler LogoffCompleted;
        
        /// <remarks/>
        public event LogonCompletedEventHandler LogonCompleted;
        
        /// <remarks/>
        public event RequiredLogonCompletedEventHandler RequiredLogonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/ValidateABA", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidateABA(string token, string aba) {
            object[] results = this.Invoke("ValidateABA", new object[] {
                        token,
                        aba});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateABAAsync(string token, string aba) {
            this.ValidateABAAsync(token, aba, null);
        }
        
        /// <remarks/>
        public void ValidateABAAsync(string token, string aba, object userState) {
            if ((this.ValidateABAOperationCompleted == null)) {
                this.ValidateABAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateABAOperationCompleted);
            }
            this.InvokeAsync("ValidateABA", new object[] {
                        token,
                        aba}, this.ValidateABAOperationCompleted, userState);
        }
        
        private void OnValidateABAOperationCompleted(object arg) {
            if ((this.ValidateABACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateABACompleted(this, new ValidateABACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/VerifyABA", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyABA(string token, string aba) {
            object[] results = this.Invoke("VerifyABA", new object[] {
                        token,
                        aba});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyABAAsync(string token, string aba) {
            this.VerifyABAAsync(token, aba, null);
        }
        
        /// <remarks/>
        public void VerifyABAAsync(string token, string aba, object userState) {
            if ((this.VerifyABAOperationCompleted == null)) {
                this.VerifyABAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyABAOperationCompleted);
            }
            this.InvokeAsync("VerifyABA", new object[] {
                        token,
                        aba}, this.VerifyABAOperationCompleted, userState);
        }
        
        private void OnVerifyABAOperationCompleted(object arg) {
            if ((this.VerifyABACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyABACompleted(this, new VerifyABACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/VerifyWire", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VerifyWire(string token, string aba) {
            object[] results = this.Invoke("VerifyWire", new object[] {
                        token,
                        aba});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyWireAsync(string token, string aba) {
            this.VerifyWireAsync(token, aba, null);
        }
        
        /// <remarks/>
        public void VerifyWireAsync(string token, string aba, object userState) {
            if ((this.VerifyWireOperationCompleted == null)) {
                this.VerifyWireOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyWireOperationCompleted);
            }
            this.InvokeAsync("VerifyWire", new object[] {
                        token,
                        aba}, this.VerifyWireOperationCompleted, userState);
        }
        
        private void OnVerifyWireOperationCompleted(object arg) {
            if ((this.VerifyWireCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyWireCompleted(this, new VerifyWireCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/GetBanksForEW", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBanksForEW(string token, string aba) {
            object[] results = this.Invoke("GetBanksForEW", new object[] {
                        token,
                        aba});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBanksForEWAsync(string token, string aba) {
            this.GetBanksForEWAsync(token, aba, null);
        }
        
        /// <remarks/>
        public void GetBanksForEWAsync(string token, string aba, object userState) {
            if ((this.GetBanksForEWOperationCompleted == null)) {
                this.GetBanksForEWOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBanksForEWOperationCompleted);
            }
            this.InvokeAsync("GetBanksForEW", new object[] {
                        token,
                        aba}, this.GetBanksForEWOperationCompleted, userState);
        }
        
        private void OnGetBanksForEWOperationCompleted(object arg) {
            if ((this.GetBanksForEWCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBanksForEWCompleted(this, new GetBanksForEWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/GetBanksXML", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBanksXML(string token, string aba) {
            object[] results = this.Invoke("GetBanksXML", new object[] {
                        token,
                        aba});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBanksXMLAsync(string token, string aba) {
            this.GetBanksXMLAsync(token, aba, null);
        }
        
        /// <remarks/>
        public void GetBanksXMLAsync(string token, string aba, object userState) {
            if ((this.GetBanksXMLOperationCompleted == null)) {
                this.GetBanksXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBanksXMLOperationCompleted);
            }
            this.InvokeAsync("GetBanksXML", new object[] {
                        token,
                        aba}, this.GetBanksXMLOperationCompleted, userState);
        }
        
        private void OnGetBanksXMLOperationCompleted(object arg) {
            if ((this.GetBanksXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBanksXMLCompleted(this, new GetBanksXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/GetBanksPrimarySortXML", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBanksPrimarySortXML(string token, string aba) {
            object[] results = this.Invoke("GetBanksPrimarySortXML", new object[] {
                        token,
                        aba});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBanksPrimarySortXMLAsync(string token, string aba) {
            this.GetBanksPrimarySortXMLAsync(token, aba, null);
        }
        
        /// <remarks/>
        public void GetBanksPrimarySortXMLAsync(string token, string aba, object userState) {
            if ((this.GetBanksPrimarySortXMLOperationCompleted == null)) {
                this.GetBanksPrimarySortXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBanksPrimarySortXMLOperationCompleted);
            }
            this.InvokeAsync("GetBanksPrimarySortXML", new object[] {
                        token,
                        aba}, this.GetBanksPrimarySortXMLOperationCompleted, userState);
        }
        
        private void OnGetBanksPrimarySortXMLOperationCompleted(object arg) {
            if ((this.GetBanksPrimarySortXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBanksPrimarySortXMLCompleted(this, new GetBanksPrimarySortXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/GetBanksXML_W3C", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBanksXML_W3C(string token, string aba) {
            object[] results = this.Invoke("GetBanksXML_W3C", new object[] {
                        token,
                        aba});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBanksXML_W3CAsync(string token, string aba) {
            this.GetBanksXML_W3CAsync(token, aba, null);
        }
        
        /// <remarks/>
        public void GetBanksXML_W3CAsync(string token, string aba, object userState) {
            if ((this.GetBanksXML_W3COperationCompleted == null)) {
                this.GetBanksXML_W3COperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBanksXML_W3COperationCompleted);
            }
            this.InvokeAsync("GetBanksXML_W3C", new object[] {
                        token,
                        aba}, this.GetBanksXML_W3COperationCompleted, userState);
        }
        
        private void OnGetBanksXML_W3COperationCompleted(object arg) {
            if ((this.GetBanksXML_W3CCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBanksXML_W3CCompleted(this, new GetBanksXML_W3CCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/GetBanksWithWireXML", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBanksWithWireXML(string token, string aba) {
            object[] results = this.Invoke("GetBanksWithWireXML", new object[] {
                        token,
                        aba});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBanksWithWireXMLAsync(string token, string aba) {
            this.GetBanksWithWireXMLAsync(token, aba, null);
        }
        
        /// <remarks/>
        public void GetBanksWithWireXMLAsync(string token, string aba, object userState) {
            if ((this.GetBanksWithWireXMLOperationCompleted == null)) {
                this.GetBanksWithWireXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBanksWithWireXMLOperationCompleted);
            }
            this.InvokeAsync("GetBanksWithWireXML", new object[] {
                        token,
                        aba}, this.GetBanksWithWireXMLOperationCompleted, userState);
        }
        
        private void OnGetBanksWithWireXMLOperationCompleted(object arg) {
            if ((this.GetBanksWithWireXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBanksWithWireXMLCompleted(this, new GetBanksWithWireXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/GetBanksWithWireXML_W3C", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBanksWithWireXML_W3C(string token, string aba) {
            object[] results = this.Invoke("GetBanksWithWireXML_W3C", new object[] {
                        token,
                        aba});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBanksWithWireXML_W3CAsync(string token, string aba) {
            this.GetBanksWithWireXML_W3CAsync(token, aba, null);
        }
        
        /// <remarks/>
        public void GetBanksWithWireXML_W3CAsync(string token, string aba, object userState) {
            if ((this.GetBanksWithWireXML_W3COperationCompleted == null)) {
                this.GetBanksWithWireXML_W3COperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBanksWithWireXML_W3COperationCompleted);
            }
            this.InvokeAsync("GetBanksWithWireXML_W3C", new object[] {
                        token,
                        aba}, this.GetBanksWithWireXML_W3COperationCompleted, userState);
        }
        
        private void OnGetBanksWithWireXML_W3COperationCompleted(object arg) {
            if ((this.GetBanksWithWireXML_W3CCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBanksWithWireXML_W3CCompleted(this, new GetBanksWithWireXML_W3CCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/FindASCompanyID", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int FindASCompanyID(string serialNumber, string payeeCode) {
            object[] results = this.Invoke("FindASCompanyID", new object[] {
                        serialNumber,
                        payeeCode});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FindASCompanyIDAsync(string serialNumber, string payeeCode) {
            this.FindASCompanyIDAsync(serialNumber, payeeCode, null);
        }
        
        /// <remarks/>
        public void FindASCompanyIDAsync(string serialNumber, string payeeCode, object userState) {
            if ((this.FindASCompanyIDOperationCompleted == null)) {
                this.FindASCompanyIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindASCompanyIDOperationCompleted);
            }
            this.InvokeAsync("FindASCompanyID", new object[] {
                        serialNumber,
                        payeeCode}, this.FindASCompanyIDOperationCompleted, userState);
        }
        
        private void OnFindASCompanyIDOperationCompleted(object arg) {
            if ((this.FindASCompanyIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindASCompanyIDCompleted(this, new FindASCompanyIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/FindCompanyID", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int FindCompanyID(string wildcard) {
            object[] results = this.Invoke("FindCompanyID", new object[] {
                        wildcard});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void FindCompanyIDAsync(string wildcard) {
            this.FindCompanyIDAsync(wildcard, null);
        }
        
        /// <remarks/>
        public void FindCompanyIDAsync(string wildcard, object userState) {
            if ((this.FindCompanyIDOperationCompleted == null)) {
                this.FindCompanyIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindCompanyIDOperationCompleted);
            }
            this.InvokeAsync("FindCompanyID", new object[] {
                        wildcard}, this.FindCompanyIDOperationCompleted, userState);
        }
        
        private void OnFindCompanyIDOperationCompleted(object arg) {
            if ((this.FindCompanyIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindCompanyIDCompleted(this, new FindCompanyIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/GetCompanyID", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetCompanyID(string token) {
            object[] results = this.Invoke("GetCompanyID", new object[] {
                        token});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompanyIDAsync(string token) {
            this.GetCompanyIDAsync(token, null);
        }
        
        /// <remarks/>
        public void GetCompanyIDAsync(string token, object userState) {
            if ((this.GetCompanyIDOperationCompleted == null)) {
                this.GetCompanyIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompanyIDOperationCompleted);
            }
            this.InvokeAsync("GetCompanyID", new object[] {
                        token}, this.GetCompanyIDOperationCompleted, userState);
        }
        
        private void OnGetCompanyIDOperationCompleted(object arg) {
            if ((this.GetCompanyIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompanyIDCompleted(this, new GetCompanyIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/Logoff", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Logoff(string token) {
            this.Invoke("Logoff", new object[] {
                        token});
        }
        
        /// <remarks/>
        public void LogoffAsync(string token) {
            this.LogoffAsync(token, null);
        }
        
        /// <remarks/>
        public void LogoffAsync(string token, object userState) {
            if ((this.LogoffOperationCompleted == null)) {
                this.LogoffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoffOperationCompleted);
            }
            this.InvokeAsync("Logoff", new object[] {
                        token}, this.LogoffOperationCompleted, userState);
        }
        
        private void OnLogoffOperationCompleted(object arg) {
            if ((this.LogoffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogoffCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/Logon", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Logon(int companyID, string userName, string password) {
            object[] results = this.Invoke("Logon", new object[] {
                        companyID,
                        userName,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LogonAsync(int companyID, string userName, string password) {
            this.LogonAsync(companyID, userName, password, null);
        }
        
        /// <remarks/>
        public void LogonAsync(int companyID, string userName, string password, object userState) {
            if ((this.LogonOperationCompleted == null)) {
                this.LogonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogonOperationCompleted);
            }
            this.InvokeAsync("Logon", new object[] {
                        companyID,
                        userName,
                        password}, this.LogonOperationCompleted, userState);
        }
        
        private void OnLogonOperationCompleted(object arg) {
            if ((this.LogonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogonCompleted(this, new LogonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.lyonsreg.com/WebService/ABAService/RequiredLogon", RequestNamespace="http://www.lyonsreg.com/WebService/ABAService", ResponseNamespace="http://www.lyonsreg.com/WebService/ABAService", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RequiredLogon(string token) {
            object[] results = this.Invoke("RequiredLogon", new object[] {
                        token});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RequiredLogonAsync(string token) {
            this.RequiredLogonAsync(token, null);
        }
        
        /// <remarks/>
        public void RequiredLogonAsync(string token, object userState) {
            if ((this.RequiredLogonOperationCompleted == null)) {
                this.RequiredLogonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequiredLogonOperationCompleted);
            }
            this.InvokeAsync("RequiredLogon", new object[] {
                        token}, this.RequiredLogonOperationCompleted, userState);
        }
        
        private void OnRequiredLogonOperationCompleted(object arg) {
            if ((this.RequiredLogonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequiredLogonCompleted(this, new RequiredLogonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ValidateABACompletedEventHandler(object sender, ValidateABACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateABACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateABACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void VerifyABACompletedEventHandler(object sender, VerifyABACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyABACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyABACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void VerifyWireCompletedEventHandler(object sender, VerifyWireCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyWireCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyWireCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetBanksForEWCompletedEventHandler(object sender, GetBanksForEWCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBanksForEWCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBanksForEWCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetBanksXMLCompletedEventHandler(object sender, GetBanksXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBanksXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBanksXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetBanksPrimarySortXMLCompletedEventHandler(object sender, GetBanksPrimarySortXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBanksPrimarySortXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBanksPrimarySortXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetBanksXML_W3CCompletedEventHandler(object sender, GetBanksXML_W3CCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBanksXML_W3CCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBanksXML_W3CCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetBanksWithWireXMLCompletedEventHandler(object sender, GetBanksWithWireXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBanksWithWireXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBanksWithWireXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetBanksWithWireXML_W3CCompletedEventHandler(object sender, GetBanksWithWireXML_W3CCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBanksWithWireXML_W3CCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBanksWithWireXML_W3CCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FindASCompanyIDCompletedEventHandler(object sender, FindASCompanyIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindASCompanyIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindASCompanyIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void FindCompanyIDCompletedEventHandler(object sender, FindCompanyIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindCompanyIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindCompanyIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetCompanyIDCompletedEventHandler(object sender, GetCompanyIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompanyIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompanyIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void LogoffCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void LogonCompletedEventHandler(object sender, LogonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void RequiredLogonCompletedEventHandler(object sender, RequiredLogonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequiredLogonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequiredLogonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591